import { chromium } from 'playwright';
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
const errs = []; page.on('pageerror', e => errs.push(String(e)));
await page.goto('http://localhost:8787/?dev=1&warp=3200');
await new Promise(r => setTimeout(r, 2500));
try { if (await page.isVisible('#intro')) await page.click('#btn-skip', {timeout:3000}); } catch(_){}
await page.click('#btn-start'); await new Promise(r => setTimeout(r, 400));
await page.click('#btn-go'); await new Promise(r => setTimeout(r, 900));
await page.keyboard.down('KeyD'); await new Promise(r => setTimeout(r, 900)); await page.keyboard.up('KeyD');
await new Promise(r => setTimeout(r, 1000));
await page.screenshot({ path: '/home/claude/apocalypse-meow/work/fps_enter.png' });
await page.keyboard.down('KeyW'); await new Promise(r => setTimeout(r, 1100));
await page.keyboard.down('KeyD'); await new Promise(r => setTimeout(r, 450)); await page.keyboard.up('KeyD');
await new Promise(r => setTimeout(r, 700)); await page.keyboard.up('KeyW');
await page.keyboard.down('KeyJ'); await new Promise(r => setTimeout(r, 250));
await page.screenshot({ path: '/home/claude/apocalypse-meow/work/fps_fire.png' });
await page.keyboard.up('KeyJ');
console.log('errors:', errs);
await browser.close();
